name: Deploy Laravel using SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: ocd
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          ls
          git clone git@github.com:lg0killer/PhotographyCMS.git
          ls
